name: Barium-CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install C and C++ header files
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-multilib
      if: matrix.install-headerfiles
    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get install cmake
        sudo apt-get install flex
        # sudo apt-get install bison
        sudo apt-get install lld
        sudo apt-get install llvm
        wget http://ftp.gnu.org/gnu/bison/bison-3.5.tar.gz
        tar -zxvf bison-3.5.tar.gz
        cd bison-3.5 && ./configure && make && sudo make install 
    - name: Build the target
      run: |
        make
    - meow: Test run
      run: |
        ./build/src/barium test_files/test.bar
