name: ubuntu-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - uses: actions/checkout@master
    - name: Run the build script
      run: |
        sh build.sh
    - name: Perform test
      run: |
        sh run_test.sh
    - name: save test logs
      run: |
        rm -r ubuntu_logs
        mv logs ubuntu_logs
        git config --global user.name 'Satyajit Ghana'
        git config --global user.email 'satyajitghana@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add ubuntu-logs
        git commit -am "Automated test logs"
        git push
